let solarCharm = [
  {
    title: "There is No Wind",
    statMin: "Archery 4, Essence 1",
    preReq: "none",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "nullify penalties to ranged attack"
  },
  {
    title: "Accuracy Without Distance",
    statMin: "Archery 5, Essence 3",
    preReq: "There is No Wind",
    essenceCost: 4,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "Ranged attack hits a valid target, soak and hardness still apply to damage"
  },
  {
    title: "Forceful Arrow",
    statMin: "Archery 4, Essence 2",
    preReq: "There is No Wind",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "a target hit by the attack, is pushed back (Essence * 3) yards if they take damage."
  },
  {
    title: "Trance of Unhesitating Speed",
    statMin: "Archery 3, Essence 2",
    preReq: "Archery Excellency",
    essenceCost: 2,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "convert 1 attack, into a flurry of (Essence + 1) attacks with no multiple attack penalties."
  },
  {
    title: "Arrow Storm Technique",
    statMin: "Archery 5, Essence 2",
    preReq: "Trance of Unhesitating Speed",
    essenceCost: 5,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "1 attack is rolled to hit (Essence x 3) targets, but never a single target or human sized target more than once."
  },
  {
    title: "Flashing Vengeance Draw",
    statMin: "Archery 3, Essence 2",
    preReq: "Trance of Unhesitating Speed",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "add Essence in autosuccesses to Join Battle, if first in line the first attack is made with 'unexpected attack' bonuses."
  },
  {
    title: "Essence Arrow Attack",
    statMin: "Archery 2, Essence 2",
    preReq: "none",
    essenceCost: 2,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Add Essence to weapon damage, and choose 1: (Fiery Arrow Attack: attack lights flammable objects), (Dazzling Flare: Solar illuminates Essence * 10 yards), (Righteous Judgement Arrow: spend +1m to add 4dmg dice)"
  },
  {
   title: "Phantom Arrow Technique",
    statMin: "Archery 3, Essence 2",
    preReq: "Essence Arrow Attack",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "create 1 ammunition of any kind out of essence for an attack."
  },
  {
    title: "Summoning the Loyal Bow",
    statMin: "Archery 3, Essence 2",
    preReq: "Phantom Arrow Technique",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Store bow in Elsewhere to be pulled later."
  },
  {
    title: "Immaculate Golden Bow",
    statMin: "Archery 4, Essence 3",
    preReq: "Essence Arrow Attack",
    essenceCost: 3,
    willpowerCost: 2,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "create an artifact bow of your choosing out of your essence"
  },
   {
    title: "Inexhaustible Bolts of Solar Fire",
    statMin: "Archery 5, Essence 4",
    preReq: "Phantom Arrow Technique",
    essenceCost: 8,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Create a Quiver of Arrows out of essence, functions like Phantom Arrow Technique, but does not require 1m per attack."
  }, {
    title: "Solar Flare Methodology",
    statMin: "Archery 4, Essence 3",
    preReq: "Essence Arrow Attack",
    essenceCost: 3,
    willpowerCost: 2,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Create a firewand or similar artifact weapon out of essence."
  }, {
    title: "Rain of Feathered Death",
    statMin: "Archery 4, Essence 3",
    preReq: "Phantom Arrow Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "duplicate up to Essence of an attack, roll once to hit, then roll damage for each separately."
  }, {
    title: "Lambent Bold of Annihilation",
    statMin: "Archery 5, Essence 4",
    preReq: "Essence Arrow Attack",
    essenceCost: 5,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "A successful attack w/ this charm causes an Environmental Attack of (Essence * 5) yards, (Essence) L dmg, and (Essence) Trauma."
  }, {
    title: "Golden Artillerist Method",
    statMin: "Archery 5, Essence 5",
    preReq: "Phantom Arrow Technique",
    essenceCost: 0,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "0",
    attribute: "0",
    perfect: "false",
    effect: "The solar can use any ranged weapon they touch flawlessly, person-scale weaponry requires 3m per attack, artillery-scale weaponry requires 3m 1wp per attack."
  }, {
    title: "Boundless Arrow of the Unconquered Sun",
    statMin: "Archery 7, Essence 7",
    preReq: "Archery Essence Flow, Phantom Arrow Technique",
    essenceCost: 13,
    willpowerCost: 2,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "true",
    effect: "On a clear day, the Solar fires an arrow at the sun, and the attack hits once the target is under a clear sky be it in Creation, Malfeas, or the Wyld. Can only be used once before the Solar sees their target again."
  }
]
