let solarMACharms = [
   {
    title: "Fists of Iron Technique",
    statMin: "Martial Arts 2, Essence 1",
    preReq: "none",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "+1 Accuracy, +2 L damage to an Unarmed Strike"
  },
   {
    title: "Sledgehammer Fist Punch",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Fists of Iron Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Double raw damage of an attack on an inanimate object."
  },
   {
    title: "Dragon Coil Technique",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Fists of Iron Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Clinch Damage is now Lethal, Solar also adds Essence to inflict, maintain, damage, and control a Clinch attacks"
  },
   {
    title: "Solar Hero Form",
    statMin: "Martial Arts 4, Essence 2",
    preReq: "Sledgehammer Fist Punch, Dragon Coil Technique",
    essenceCost: 6,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Solar doubles successes twice for unarmed attack damage, and may block lethal attacks and ranged attacks."
  },
   {
    title: "Heaven Thunder Hammer",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Solar Hero Form",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "an unarmed strike's damage pushes the enemy back (pre-soak damage success dice) yards, objects hit mid flight deal 1 die of damage either Lethal or Bashing"
  },
   {
    title: "Crashing Wave Throw",
    statMin: "Martial Arts 5, Essence 3",
    preReq: "Heaven Thunder Hammer",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "The solar ends a clinch attack and hurls target (Martial Arts * 5) yards upward, or (Martials Arts * 10) yards horizontal yards, targets take appropriate fall damage."
  },
   {
    title: "Ox-Stunning Blow",
    statMin: "Martial Arts 4, Essence 2",
    preReq: "Solar Hero Form",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "If solar hits, they can spend up to twice their Strength in Essence (1m per die), and inflicts 1 die of stunning damage per mote spent. Stunning damage ignores natural and armor soak, and every success is a -1 penalty in the target's dicepool and DV for next 3 actions."
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }
]
