let solarCharm = [
  {
    title: "There is No Wind",
    statMin: "Archery 4, Essence 1",
    preReq: "none",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "nullify penalties to ranged attack"
  },
  {
    title: "Accuracy Without Distance",
    statMin: "Archery 5, Essence 3",
    preReq: "There is No Wind",
    essenceCost: 4,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "Ranged attack hits a valid target, soak and hardness still apply to damage"
  },
  {
    title: "Forceful Arrow",
    statMin: "Archery 4, Essence 2",
    preReq: "There is No Wind",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "a target hit by the attack, is pushed back (Essence * 3) yards if they take damage."
  },
  {
    title: "Trance of Unhesitating Speed",
    statMin: "Archery 3, Essence 2",
    preReq: "Archery Excellency",
    essenceCost: 2,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "convert 1 attack, into a flurry of (Essence + 1) attacks with no multiple attack penalties."
  },
  {
    title: "Arrow Storm Technique",
    statMin: "Archery 5, Essence 2",
    preReq: "Trance of Unhesitating Speed",
    essenceCost: 5,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "Dexterity",
    attribute: "Archery",
    perfect: "false",
    effect: "1 attack is rolled to hit (Essence x 3) targets, but never a single target or human sized target more than once."
  },
  {
    title: "Flashing Vengeance Draw",
    statMin: "Archery 3, Essence 2",
    preReq: "Trance of Unhesitating Speed",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "add Essence in autosuccesses to Join Battle, if first in line the first attack is made with 'unexpected attack' bonuses."
  },
  {
    title: "Essence Arrow Attack",
    statMin: "Archery 2, Essence 2",
    preReq: "none",
    essenceCost: 2,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Add Essence to weapon damage, and choose 1: (Fiery Arrow Attack: attack lights flammable objects), (Dazzling Flare: Solar illuminates Essence * 10 yards), (Righteous Judgement Arrow: spend +1m to add 4dmg dice)"
  },
  {
   title: "Phantom Arrow Technique",
    statMin: "Archery 3, Essence 2",
    preReq: "Essence Arrow Attack",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "create 1 ammunition of any kind out of essence for an attack."
  },
  {
    title: "Summoning the Loyal Bow",
    statMin: "Archery 3, Essence 2",
    preReq: "Phantom Arrow Technique",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Store bow in Elsewhere to be pulled later."
  },
  {
    title: "Immaculate Golden Bow",
    statMin: "Archery 4, Essence 3",
    preReq: "Essence Arrow Attack",
    essenceCost: 3,
    willpowerCost: 2,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "create an artifact bow of your choosing out of your essence"
  },
   {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }, {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }, {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }, {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }, {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }, {
    title: "x",
    statMin: "",
    preReq: "y",
    essenceCost: "e",
    willpowerCost: "w",
    healthLevelCost: "h",
    ability: "aB",
    attribute: "aT",
    perfect: "true/false",
    effect: ""
  }
]
