let solarMACharms = [
   {
    title: "Fists of Iron Technique",
    ability: "Martial Arts",
    attribute: "none",
    abilityValRequirement: 2,
    essenceValRequirement: 1,
    preReq: "none",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    abilityRolled: "none",
    attributeRolled: "none",
    perfect: "false",
    effect: "+1 Accuracy, +2 L damage to an Unarmed Strike"
  },
   //As done above, change the statMin key, to 'ability' , 'attribute' , 'abilityValRequirement' , and 'essenceValRequirement'. Add to the rest
   {
    title: "Sledgehammer Fist Punch",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Fists of Iron Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Double raw damage of an attack on an inanimate object."
  },
   {
    title: "Dragon Coil Technique",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Fists of Iron Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Clinch Damage is now Lethal, Solar also adds Essence to inflict, maintain, damage, and control a Clinch attacks"
  },
   {
    title: "Solar Hero Form",
    statMin: "Martial Arts 4, Essence 2",
    preReq: "Sledgehammer Fist Punch, Dragon Coil Technique",
    essenceCost: 6,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Solar doubles successes twice for unarmed attack damage, and may block lethal attacks and ranged attacks."
  },
   {
    title: "Heaven Thunder Hammer",
    statMin: "Martial Arts 3, Essence 2",
    preReq: "Solar Hero Form",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "an unarmed strike's damage pushes the enemy back (pre-soak damage success dice) yards, objects hit mid flight deal 1 die of damage either Lethal or Bashing"
  },
   {
    title: "Crashing Wave Throw",
    statMin: "Martial Arts 5, Essence 3",
    preReq: "Heaven Thunder Hammer",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "The solar ends a clinch attack and hurls target (Martial Arts * 5) yards upward, or (Martials Arts * 10) yards horizontal yards, targets take appropriate fall damage."
  },
   {
    title: "Ox-Stunning Blow",
    statMin: "Martial Arts 4, Essence 2",
    preReq: "Solar Hero Form",
    essenceCost: 1,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "If solar hits, they can spend up to twice their Strength in Essence (1m per die), and inflicts 1 die of stunning damage per mote spent. Stunning damage ignores natural and armor soak, and every success is a -1 penalty in the target's dicepool and DV for next 3 actions."
  },
   {
    title: "Hammer on Iron Technique",
    statMin: "Martial Arts 4, Essence 2",
    preReq: "Solar Hero Form",
    essenceCost: 3,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "A martial arts flurry attack charm, Exalt makes (Essence + 1) attacks against a single target, without taking multiple action penalties and regardless of attack rating."
  },
   {
    title: "Shockwave Technique",
    statMin: "Martial Arts 5, Essence 3",
    preReq: "Crashing Wave Throw, Ox-Stunning Blow, Hammer on Iron Technique",
    essenceCost: 3,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "true",
    effect: "Unblockable, if the first attack hits, the Exalt throws their target up to (Martial Arts * 5) yards into a second target, the first target is treated as a weapon with Acc - 3, +4B damage. If the first attack misses, then the target instead travels the full distance with effects from Heaven Thunder Hammer applied. The target cannot retaliate with counterattack charms."
  },
   {
    title: "Solar Hero Supremacy",
    statMin: "Martial Arts 5, Essence 5",
    preReq: "Fists of Iron Technique",
    essenceCost: 0,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "Permanent effect; The Exalts unarmed attacks, that hit or roll damage on a target, now automatically apply a -2 penalty until the Solar's next turn, this is a cumulative effect that compiles with each successful blow on a turn."
  },
   {
    title: "Armor-Shattering Strike",
    statMin: "Martial Arts 5, Essence 3",
    preReq: "Solar Hero Form",
    essenceCost: 4,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "A successful attack w/ this charm, shatters nonmagical armor in an explosion of shrapnel or scraps. An additional 1 mote of essence may be spent to end all charms, spells, and astrological effects that are greater than (instant), but less than (permanent) duration, that provide  increased soak and hardness. This nullification is a Shaping Effect."
  },
   {
    title: "Iron Talon Technique",
    statMin: "Martial Arts 6, Essence 6",
    preReq: "Dragon Coil Technique",
    essenceCost: 5,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "You have a bonus to  maintain or gain control of an ongoing grapple, w/ and automatic threshold of 1 success more than your opponent. If another effect contests this, add Essence in extra dice to the resulting roll."
  },
   {
    title: "Swallowing the Lotus Root",
    statMin: "Martial Arts 5, Essence 2",
    preReq: "none",
    essenceCost: 0,
    willpowerCost: 0,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "reduced cost for Terrestrial Martial Arts forms to 5xp, 4xp if favored, and Training time is halved."
  },
   {
    title: "Orichalcum Fists of Battle",
    statMin: "Martial Arts 6, Essence 6",
    preReq: "Solar Hero Supremacy",
    essenceCost: 10,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "Strength",
    attribute: "none",
    perfect: "false",
    effect: "Solar multiplies (Strength * Essence) when calculating raw damage of unarmed attacks, these attacks ignore hardness."
  },
   {
    title: "Wicked Fists of Battle",
    statMin: "Martial Arts 7, Essence 7",
    preReq: "Solar Hero Supremacy",
    essenceCost: 1,
    willpowerCost: 1,
    healthLevelCost: 0,
    ability: "none",
    attribute: "none",
    perfect: "false",
    effect: "This Charm constitutes a monstrous blow which raises a massive cloud of dust and debris on impact, knocking the opponent senseless. The target is rendered Inactive for a number of ticks equal to the post-soak damage dice of the attack (rounded up). Wicked Dissolve Dust may only be activated if the target suffers a stunning penalty (such as from Solar Hero Supremacy) higher than their Stamina rating."
  }
]
